require('@solana/wallet-adapter-react-ui/styles.css');
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import SolanaWalletProvider from "./providers/SolanaWalletProvider";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <SolanaWalletProvider>
        <body className={`${inter.className} overflow-x-hidden`}>
          <header>
            <Header />
          </header>
          <main>
            {children}
          </main>
        </body>
      </SolanaWalletProvider>
    </html>
  );
}
